---
- name: "Disable swapoff"
  shell: swapoff -a
  become: true

- name: "Configure Limits"
  pam_limits:
    domain: elasticsearch
    limit_type: hard
    limit_item: nofile
    value: '65535'
  become: true

- name: "Create oveeride folder for systemd elaticsearch service"
  file:
    state: directory
    path: /etc/systemd/system/elasticsearch.service.d
    recurse: yes
  become: true

- name: "Copy the override configuration"
  copy:
    src: override.conf
    dest: /etc/systemd/system/elasticsearch.service.d/override.conf
  become: true
  notify: "Reload daemons"

- name: "Enforce ulimits"
  shell: ulimit -n 65535

- name: "Flush Handlers"
  meta: flush_handlers
