---
- name: "Preflight Checks"
  include_tasks: "00-preflight-checks.yml"

- name: "Install Elasticsearch"
  include_tasks: "01-install.yml"

# This will be moved in another role
# - name: "Configure Elasticsearch"
#   include_tasks: "02-configure.yml"
