---
- name: "Start Elasticsearch"
  systemd:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    state: started

- name: "Restart Elasticsearch"
  systemd:
    name: elasticsearch
    daemon_reload: yes
    state: restarted

- name: "Reload daemons"
  systemd:
    daemon_reload: yes
